// Generated by scripts/gen-types.sh from the LOCAL post-migration schema; do not edit by hand.
// CI regenerates this file and fails when the committed copy drifts.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      case_facts: {
        Row: {
          created_at: string;
          fact_key: string;
          fact_value: string | null;
          id: string;
          intake_document_id: string | null;
          requirement_id: string;
          source: string | null;
          workspace_id: string;
        };
        Insert: {
          created_at?: string;
          fact_key: string;
          fact_value?: string | null;
          id?: string;
          intake_document_id?: string | null;
          requirement_id: string;
          source?: string | null;
          workspace_id: string;
        };
        Update: {
          created_at?: string;
          fact_key?: string;
          fact_value?: string | null;
          id?: string;
          intake_document_id?: string | null;
          requirement_id?: string;
          source?: string | null;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "case_facts_intake_document_id_fkey";
            columns: ["intake_document_id"];
            isOneToOne: false;
            referencedRelation: "intake_documents";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "case_facts_requirement_id_fkey";
            columns: ["requirement_id"];
            isOneToOne: false;
            referencedRelation: "requirements";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "case_facts_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      clarification_questions: {
        Row: {
          answer: string | null;
          created_at: string;
          id: string;
          question: string;
          requirement_id: string;
          status: Database["public"]["Enums"]["clarification_question_status"];
          workspace_id: string;
        };
        Insert: {
          answer?: string | null;
          created_at?: string;
          id?: string;
          question: string;
          requirement_id: string;
          status?: Database["public"]["Enums"]["clarification_question_status"];
          workspace_id: string;
        };
        Update: {
          answer?: string | null;
          created_at?: string;
          id?: string;
          question?: string;
          requirement_id?: string;
          status?: Database["public"]["Enums"]["clarification_question_status"];
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "clarification_questions_requirement_id_fkey";
            columns: ["requirement_id"];
            isOneToOne: false;
            referencedRelation: "requirements";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "clarification_questions_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      draft_attachments: {
        Row: {
          created_at: string;
          created_by: string;
          deleted_at: string | null;
          draft_id: string;
          id: string;
          mime_type: string;
          original_filename: string;
          safe_filename: string;
          sha256: string | null;
          size_bytes: number;
          status: string;
          storage_bucket: string;
          storage_path: string;
          verified_at: string | null;
          workspace_id: string;
        };
        Insert: {
          created_at?: string;
          created_by: string;
          deleted_at?: string | null;
          draft_id: string;
          id?: string;
          mime_type: string;
          original_filename: string;
          safe_filename: string;
          sha256?: string | null;
          size_bytes: number;
          status?: string;
          storage_bucket?: string;
          storage_path: string;
          verified_at?: string | null;
          workspace_id: string;
        };
        Update: {
          created_at?: string;
          created_by?: string;
          deleted_at?: string | null;
          draft_id?: string;
          id?: string;
          mime_type?: string;
          original_filename?: string;
          safe_filename?: string;
          sha256?: string | null;
          size_bytes?: number;
          status?: string;
          storage_bucket?: string;
          storage_path?: string;
          verified_at?: string | null;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "draft_attachments_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "draft_attachments_draft_id_fkey";
            columns: ["draft_id"];
            isOneToOne: false;
            referencedRelation: "drafts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "draft_attachments_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      draft_template_versions: {
        Row: {
          body_template_json: Json;
          created_at: string;
          created_by: string;
          id: string;
          subject_template: string;
          template_id: string;
          variable_schema: Json;
          version_no: number;
          workspace_id: string;
        };
        Insert: {
          body_template_json: Json;
          created_at?: string;
          created_by: string;
          id?: string;
          subject_template?: string;
          template_id: string;
          variable_schema?: Json;
          version_no: number;
          workspace_id: string;
        };
        Update: {
          body_template_json?: Json;
          created_at?: string;
          created_by?: string;
          id?: string;
          subject_template?: string;
          template_id?: string;
          variable_schema?: Json;
          version_no?: number;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "draft_template_versions_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "draft_template_versions_template_id_fkey";
            columns: ["template_id"];
            isOneToOne: false;
            referencedRelation: "draft_templates";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "draft_template_versions_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      draft_templates: {
        Row: {
          archived_at: string | null;
          created_at: string;
          created_by: string;
          description: string | null;
          id: string;
          name: string;
          updated_at: string;
          workspace_id: string;
        };
        Insert: {
          archived_at?: string | null;
          created_at?: string;
          created_by: string;
          description?: string | null;
          id?: string;
          name: string;
          updated_at?: string;
          workspace_id: string;
        };
        Update: {
          archived_at?: string | null;
          created_at?: string;
          created_by?: string;
          description?: string | null;
          id?: string;
          name?: string;
          updated_at?: string;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "draft_templates_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "draft_templates_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      draft_versions: {
        Row: {
          body_json: Json;
          created_at: string;
          created_by: string;
          draft_id: string;
          id: string;
          reason: string;
          source_revision: number;
          subject: string;
          version_no: number;
          workspace_id: string;
        };
        Insert: {
          body_json: Json;
          created_at?: string;
          created_by: string;
          draft_id: string;
          id?: string;
          reason: string;
          source_revision: number;
          subject: string;
          version_no: number;
          workspace_id: string;
        };
        Update: {
          body_json?: Json;
          created_at?: string;
          created_by?: string;
          draft_id?: string;
          id?: string;
          reason?: string;
          source_revision?: number;
          subject?: string;
          version_no?: number;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "draft_versions_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "draft_versions_draft_id_fkey";
            columns: ["draft_id"];
            isOneToOne: false;
            referencedRelation: "drafts";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "draft_versions_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      drafts: {
        Row: {
          archived_at: string | null;
          body_json: Json;
          created_at: string;
          created_by: string;
          id: string;
          last_autosaved_at: string | null;
          last_signature_id: string | null;
          last_template_version_id: string | null;
          revision: number;
          status: string;
          subject: string;
          updated_at: string;
          updated_by: string;
          workspace_id: string;
        };
        Insert: {
          archived_at?: string | null;
          body_json: Json;
          created_at?: string;
          created_by: string;
          id?: string;
          last_autosaved_at?: string | null;
          last_signature_id?: string | null;
          last_template_version_id?: string | null;
          revision?: number;
          status?: string;
          subject?: string;
          updated_at?: string;
          updated_by: string;
          workspace_id: string;
        };
        Update: {
          archived_at?: string | null;
          body_json?: Json;
          created_at?: string;
          created_by?: string;
          id?: string;
          last_autosaved_at?: string | null;
          last_signature_id?: string | null;
          last_template_version_id?: string | null;
          revision?: number;
          status?: string;
          subject?: string;
          updated_at?: string;
          updated_by?: string;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "drafts_created_by_fkey";
            columns: ["created_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "drafts_updated_by_fkey";
            columns: ["updated_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "drafts_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      intake_documents: {
        Row: {
          created_at: string;
          file_name: string;
          id: string;
          mime_type: string | null;
          status: Database["public"]["Enums"]["intake_document_status"];
          storage_path: string | null;
          uploaded_by: string | null;
          workspace_id: string;
        };
        Insert: {
          created_at?: string;
          file_name: string;
          id?: string;
          mime_type?: string | null;
          status?: Database["public"]["Enums"]["intake_document_status"];
          storage_path?: string | null;
          uploaded_by?: string | null;
          workspace_id: string;
        };
        Update: {
          created_at?: string;
          file_name?: string;
          id?: string;
          mime_type?: string | null;
          status?: Database["public"]["Enums"]["intake_document_status"];
          storage_path?: string | null;
          uploaded_by?: string | null;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "intake_documents_uploaded_by_fkey";
            columns: ["uploaded_by"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "intake_documents_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      notification_preferences: {
        Row: {
          channel: Database["public"]["Enums"]["notification_channel"];
          created_at: string;
          enabled: boolean;
          id: string;
          user_id: string;
          workspace_id: string;
        };
        Insert: {
          channel: Database["public"]["Enums"]["notification_channel"];
          created_at?: string;
          enabled?: boolean;
          id?: string;
          user_id: string;
          workspace_id: string;
        };
        Update: {
          channel?: Database["public"]["Enums"]["notification_channel"];
          created_at?: string;
          enabled?: boolean;
          id?: string;
          user_id?: string;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notification_preferences_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notification_preferences_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      notifications: {
        Row: {
          body: string | null;
          created_at: string;
          id: string;
          read_at: string | null;
          related_task_id: string | null;
          title: string;
          type: string;
          user_id: string;
          workspace_id: string;
        };
        Insert: {
          body?: string | null;
          created_at?: string;
          id?: string;
          read_at?: string | null;
          related_task_id?: string | null;
          title: string;
          type: string;
          user_id: string;
          workspace_id: string;
        };
        Update: {
          body?: string | null;
          created_at?: string;
          id?: string;
          read_at?: string | null;
          related_task_id?: string | null;
          title?: string;
          type?: string;
          user_id?: string;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "notifications_related_task_id_fkey";
            columns: ["related_task_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notifications_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "notifications_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      reminders: {
        Row: {
          created_at: string;
          id: string;
          remind_at: string;
          status: Database["public"]["Enums"]["reminder_status"];
          task_id: string | null;
          workspace_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          remind_at: string;
          status?: Database["public"]["Enums"]["reminder_status"];
          task_id?: string | null;
          workspace_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          remind_at?: string;
          status?: Database["public"]["Enums"]["reminder_status"];
          task_id?: string | null;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "reminders_task_id_fkey";
            columns: ["task_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "reminders_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      requirements: {
        Row: {
          created_at: string;
          description: string | null;
          id: string;
          intake_document_id: string;
          is_critical: boolean;
          status: Database["public"]["Enums"]["requirement_status"];
          title: string;
          workspace_id: string;
        };
        Insert: {
          created_at?: string;
          description?: string | null;
          id?: string;
          intake_document_id: string;
          is_critical?: boolean;
          status?: Database["public"]["Enums"]["requirement_status"];
          title: string;
          workspace_id: string;
        };
        Update: {
          created_at?: string;
          description?: string | null;
          id?: string;
          intake_document_id?: string;
          is_critical?: boolean;
          status?: Database["public"]["Enums"]["requirement_status"];
          title?: string;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "requirements_intake_document_id_fkey";
            columns: ["intake_document_id"];
            isOneToOne: false;
            referencedRelation: "intake_documents";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "requirements_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      signatures: {
        Row: {
          body_json: Json;
          created_at: string;
          id: string;
          is_default: boolean;
          name: string;
          owner_user_id: string;
          updated_at: string;
          workspace_id: string;
        };
        Insert: {
          body_json: Json;
          created_at?: string;
          id?: string;
          is_default?: boolean;
          name: string;
          owner_user_id: string;
          updated_at?: string;
          workspace_id: string;
        };
        Update: {
          body_json?: Json;
          created_at?: string;
          id?: string;
          is_default?: boolean;
          name?: string;
          owner_user_id?: string;
          updated_at?: string;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "signatures_owner_user_id_fkey";
            columns: ["owner_user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "signatures_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      task_checklist_items: {
        Row: {
          created_at: string;
          id: string;
          is_complete: boolean;
          label: string;
          position: number;
          task_id: string;
          workspace_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          is_complete?: boolean;
          label: string;
          position?: number;
          task_id: string;
          workspace_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          is_complete?: boolean;
          label?: string;
          position?: number;
          task_id?: string;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "task_checklist_items_task_id_fkey";
            columns: ["task_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "task_checklist_items_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      tasks: {
        Row: {
          assigned_to: string | null;
          created_at: string;
          description: string | null;
          due_date: string | null;
          id: string;
          requirement_id: string | null;
          status: Database["public"]["Enums"]["task_status"];
          title: string;
          workspace_id: string;
        };
        Insert: {
          assigned_to?: string | null;
          created_at?: string;
          description?: string | null;
          due_date?: string | null;
          id?: string;
          requirement_id?: string | null;
          status?: Database["public"]["Enums"]["task_status"];
          title: string;
          workspace_id: string;
        };
        Update: {
          assigned_to?: string | null;
          created_at?: string;
          description?: string | null;
          due_date?: string | null;
          id?: string;
          requirement_id?: string | null;
          status?: Database["public"]["Enums"]["task_status"];
          title?: string;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tasks_assigned_to_fkey";
            columns: ["assigned_to"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_requirement_id_fkey";
            columns: ["requirement_id"];
            isOneToOne: false;
            referencedRelation: "requirements";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      users: {
        Row: {
          created_at: string;
          email: string;
          full_name: string | null;
          id: string;
        };
        Insert: {
          created_at?: string;
          email: string;
          full_name?: string | null;
          id: string;
        };
        Update: {
          created_at?: string;
          email?: string;
          full_name?: string | null;
          id?: string;
        };
        Relationships: [];
      };
      workspace_members: {
        Row: {
          created_at: string;
          id: string;
          role: Database["public"]["Enums"]["workspace_role"];
          user_id: string;
          workspace_id: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          role?: Database["public"]["Enums"]["workspace_role"];
          user_id: string;
          workspace_id: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          role?: Database["public"]["Enums"]["workspace_role"];
          user_id?: string;
          workspace_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "workspace_members_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "workspace_members_workspace_id_fkey";
            columns: ["workspace_id"];
            isOneToOne: false;
            referencedRelation: "workspaces";
            referencedColumns: ["id"];
          },
        ];
      };
      workspaces: {
        Row: {
          created_at: string;
          id: string;
          name: string;
        };
        Insert: {
          created_at?: string;
          id?: string;
          name: string;
        };
        Update: {
          created_at?: string;
          id?: string;
          name?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      archive_draft: {
        Args: {
          p_draft_id: string;
          p_expected_revision: number;
          p_workspace_id: string;
        };
        Returns: Json;
      };
      checkpoint_draft: {
        Args: {
          p_draft_id: string;
          p_expected_revision: number;
          p_reason: string;
          p_workspace_id: string;
        };
        Returns: Json;
      };
      create_attachment_intent: {
        Args: {
          p_draft_id: string;
          p_mime_type: string;
          p_original_filename: string;
          p_sha256?: string;
          p_size_bytes: number;
          p_workspace_id: string;
        };
        Returns: {
          created_at: string;
          created_by: string;
          deleted_at: string | null;
          draft_id: string;
          id: string;
          mime_type: string;
          original_filename: string;
          safe_filename: string;
          sha256: string | null;
          size_bytes: number;
          status: string;
          storage_bucket: string;
          storage_path: string;
          verified_at: string | null;
          workspace_id: string;
        };
        SetofOptions: {
          from: "*";
          to: "draft_attachments";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      create_draft: {
        Args: { p_body_json: Json; p_subject: string; p_workspace_id: string };
        Returns: {
          archived_at: string | null;
          body_json: Json;
          created_at: string;
          created_by: string;
          id: string;
          last_autosaved_at: string | null;
          last_signature_id: string | null;
          last_template_version_id: string | null;
          revision: number;
          status: string;
          subject: string;
          updated_at: string;
          updated_by: string;
          workspace_id: string;
        };
        SetofOptions: {
          from: "*";
          to: "drafts";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      create_template_version: {
        Args: {
          p_body_template_json: Json;
          p_subject_template: string;
          p_template_id: string;
          p_variable_schema: Json;
          p_workspace_id: string;
        };
        Returns: {
          body_template_json: Json;
          created_at: string;
          created_by: string;
          id: string;
          subject_template: string;
          template_id: string;
          variable_schema: Json;
          version_no: number;
          workspace_id: string;
        };
        SetofOptions: {
          from: "*";
          to: "draft_template_versions";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      finalize_attachment: {
        Args: {
          p_attachment_id: string;
          p_sha256?: string;
          p_workspace_id: string;
        };
        Returns: {
          created_at: string;
          created_by: string;
          deleted_at: string | null;
          draft_id: string;
          id: string;
          mime_type: string;
          original_filename: string;
          safe_filename: string;
          sha256: string | null;
          size_bytes: number;
          status: string;
          storage_bucket: string;
          storage_path: string;
          verified_at: string | null;
          workspace_id: string;
        };
        SetofOptions: {
          from: "*";
          to: "draft_attachments";
          isOneToOne: true;
          isSetofReturn: false;
        };
      };
      is_workspace_admin: {
        Args: { p_workspace_id: string };
        Returns: boolean;
      };
      is_workspace_member: {
        Args: { p_workspace_id: string };
        Returns: boolean;
      };
      mark_attachment_deleted: {
        Args: { p_attachment_id: string; p_workspace_id: string };
        Returns: undefined;
      };
      phase2_safe_filename: { Args: { p_input: string }; Returns: string };
      phase2_validate_variable_schema: {
        Args: { p_schema: Json };
        Returns: undefined;
      };
      restore_draft_version: {
        Args: {
          p_draft_id: string;
          p_expected_revision: number;
          p_version_id: string;
          p_workspace_id: string;
        };
        Returns: Json;
      };
      save_draft: {
        Args: {
          p_body_json: Json;
          p_draft_id: string;
          p_expected_revision: number;
          p_last_signature_id?: string;
          p_last_template_version_id?: string;
          p_save_reason: string;
          p_subject: string;
          p_workspace_id: string;
        };
        Returns: Json;
      };
      set_default_signature: {
        Args: { p_signature_id: string };
        Returns: undefined;
      };
    };
    Enums: {
      clarification_question_status: "open" | "answered" | "dismissed";
      intake_document_status: "pending" | "processing" | "processed" | "failed";
      notification_channel: "in_app" | "email";
      reminder_status: "scheduled" | "fired" | "cancelled";
      requirement_status:
        | "available"
        | "missing"
        | "uncertain"
        | "needs_confirmation"
        | "confirmed";
      task_status: "suggested" | "open" | "in_progress" | "done" | "dismissed";
      workspace_role: "owner" | "admin" | "member";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">;

type DefaultSchema = DatabaseWithoutInternals[Extract<
  keyof Database,
  "public"
>];

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I;
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I;
      }
      ? I
      : never
    : never;

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    keyof DefaultSchema["Tables"] | { schema: keyof DatabaseWithoutInternals },
  TableName extends (DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never) = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U;
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U;
      }
      ? U
      : never
    : never;

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    keyof DefaultSchema["Enums"] | { schema: keyof DatabaseWithoutInternals },
  EnumName extends (DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never) = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never;

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends (PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals;
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never) = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals;
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never;

export const Constants = {
  public: {
    Enums: {
      clarification_question_status: ["open", "answered", "dismissed"],
      intake_document_status: ["pending", "processing", "processed", "failed"],
      notification_channel: ["in_app", "email"],
      reminder_status: ["scheduled", "fired", "cancelled"],
      requirement_status: [
        "available",
        "missing",
        "uncertain",
        "needs_confirmation",
        "confirmed",
      ],
      task_status: ["suggested", "open", "in_progress", "done", "dismissed"],
      workspace_role: ["owner", "admin", "member"],
    },
  },
} as const;
