#!/usr/bin/env bash
# Regenerates src/lib/supabase/database.types.ts from the LOCAL post-migration
# schema (never from production). Requires the local test database to be
# reachable; scripts/test-db.sh --keep starts one and prints its URL.
#
# Usage:
#   DB_URL=postgresql://... pnpm gen:types
#   pnpm gen:types --check   # regenerate to a temp file and diff (CI drift gate)
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="src/lib/supabase/database.types.ts"
DB_URL="${DB_URL:-}"

if [[ -z "$DB_URL" ]]; then
  echo "DB_URL is required (local post-migration database)." >&2
  echo "Hint: bash scripts/test-db.sh --keep  # prints a DB_URL" >&2
  exit 2
fi

HEADER="// Generated by scripts/gen-types.sh from the LOCAL post-migration schema.
// Do not edit by hand. CI regenerates this file and fails on drift.
"

generate() {
  pnpm exec supabase gen types typescript --db-url "$DB_URL" --schema public
}

if [[ "${1:-}" == "--check" ]]; then
  TMP="$(mktemp)"
  trap 'rm -f "$TMP"' EXIT
  { printf '%s\n' "$HEADER"; generate; } > "$TMP"
  pnpm exec prettier --write "$TMP" --parser typescript >/dev/null
  if ! diff -u "$OUT" "$TMP"; then
    echo "ERROR: $OUT is stale. Run: DB_URL=... pnpm gen:types" >&2
    exit 1
  fi
  echo "Generated types are current."
else
  { printf '%s\n' "$HEADER"; generate; } > "$OUT"
  pnpm exec prettier --write "$OUT" >/dev/null
  echo "Wrote $OUT"
fi
