#!/usr/bin/env bash
# Regenerates src/lib/supabase/database.types.ts from the LOCAL post-migration
# schema (never from production) using the official Supabase CLI. Requires:
#   - DB_URL pointing at the local test database (scripts/test-db.sh --keep
#     starts one and prints its URL), and
#   - a working Docker daemon: `supabase gen types --db-url` pulls and runs
#     the postgres-meta image in a Docker container.
#
# Modes:
#   DB_URL=postgresql://... bash scripts/gen-types.sh
#       Write the generated types to src/lib/supabase/database.types.ts and
#       format them with prettier.
#   DB_URL=postgresql://... bash scripts/gen-types.sh --check
#       Regenerate to a temp file and compare with the committed file (CI
#       drift gate). On drift, the full generated file is printed to stdout
#       between BEGIN/END markers so it can be recovered from CI logs.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="src/lib/supabase/database.types.ts"
DB_URL="${DB_URL:-}"

if [[ -z "$DB_URL" ]]; then
  echo "DB_URL is required (local post-migration database)." >&2
  echo "Hint: bash scripts/test-db.sh --keep  # prints a DB_URL" >&2
  exit 2
fi

if ! docker info >/dev/null 2>&1; then
  echo "ERROR: Docker is not available (docker info failed)." >&2
  echo "supabase gen types --db-url runs postgres-meta in a Docker container," >&2
  echo "so a working Docker daemon is required to generate types." >&2
  exit 1
fi

HEADER="// Generated by scripts/gen-types.sh from the LOCAL post-migration schema; do not edit by hand.
// CI regenerates this file and fails when the committed copy drifts.
"

generate() {
  pnpm exec supabase gen types typescript --db-url "$DB_URL" --schema public
}

# Fail-closed validation: the Supabase CLI can print a JSON error object
# (e.g. {"_tag":"Error",...}) to stdout without exiting non-zero. Never
# accept output that does not look like the generated TypeScript module.
looks_valid() {
  local file="$1"
  grep -q 'export type Json' "$file" &&
    grep -q 'public: {' "$file" &&
    ! grep -q '"_tag":"Error"' "$file"
}

# Generation is deterministic, but fetching the postgres-meta image is not:
# anonymous registry pulls from shared CI runner IPs intermittently hit
# "toomanyrequests: Rate exceeded". Retry ONLY the generation (a drift diff
# is deterministic and is never retried).
generate_with_retry() {
  local target="$1" attempt delay
  for attempt in 1 2 3 4; do
    if { printf '%s\n' "$HEADER"; generate; } > "$target" 2> "$target.err" &&
      looks_valid "$target"; then
      rm -f "$target.err"
      return 0
    fi
    if [[ $attempt -lt 4 ]]; then
      delay=$((10 * 2 ** (attempt - 1)))
      echo "Type generation attempt $attempt failed (transient registry or" >&2
      echo "network issue?); retrying in ${delay}s..." >&2
      sleep "$delay"
    fi
  done
  echo "ERROR: type generation failed after 4 attempts." >&2
  echo "Last stdout (first 20 lines):" >&2
  head -20 "$target" >&2 || true
  echo "Last stderr (last 10 lines):" >&2
  tail -10 "$target.err" >&2 || true
  rm -f "$target.err"
  return 1
}

if [[ "${1:-}" == "--check" ]]; then
  TMP="$(mktemp)"
  trap 'rm -f "$TMP" "$TMP.err"' EXIT
  generate_with_retry "$TMP"
  pnpm exec prettier --write "$TMP" --parser typescript >/dev/null
  if ! diff -q "$OUT" "$TMP" >/dev/null; then
    echo "ERROR: $OUT is stale. Run: DB_URL=... pnpm gen:types" >&2
    echo "The freshly generated file follows so it can be recovered from CI logs:" >&2
    echo "===== BEGIN GENERATED database.types.ts ====="
    cat "$TMP"
    echo "===== END GENERATED database.types.ts ====="
    exit 1
  fi
  echo "Generated types are current."
else
  TMP="$(mktemp)"
  trap 'rm -f "$TMP" "$TMP.err"' EXIT
  generate_with_retry "$TMP"
  cat "$TMP" > "$OUT"
  pnpm exec prettier --write "$OUT" >/dev/null
  echo "Wrote $OUT"
fi
