#!/usr/bin/env bash
# Regenerates src/lib/supabase/database.types.ts from the LOCAL post-migration
# schema (never from production) using the official Supabase CLI. Requires:
#   - DB_URL pointing at the local test database (scripts/test-db.sh --keep
#     starts one and prints its URL), and
#   - a working Docker daemon: `supabase gen types --db-url` pulls and runs
#     the postgres-meta image in a Docker container.
#
# Modes:
#   DB_URL=postgresql://... bash scripts/gen-types.sh
#       Write the generated types to src/lib/supabase/database.types.ts and
#       format them with prettier.
#   DB_URL=postgresql://... bash scripts/gen-types.sh --check
#       Regenerate to a temp file and compare with the committed file (CI
#       drift gate). On drift, the full generated file is printed to stdout
#       between BEGIN/END markers so it can be recovered from CI logs.
set -euo pipefail

cd "$(dirname "$0")/.."

OUT="src/lib/supabase/database.types.ts"
DB_URL="${DB_URL:-}"

if [[ -z "$DB_URL" ]]; then
  echo "DB_URL is required (local post-migration database)." >&2
  echo "Hint: bash scripts/test-db.sh --keep  # prints a DB_URL" >&2
  exit 2
fi

if ! docker info >/dev/null 2>&1; then
  echo "ERROR: Docker is not available (docker info failed)." >&2
  echo "supabase gen types --db-url runs postgres-meta in a Docker container," >&2
  echo "so a working Docker daemon is required to generate types." >&2
  exit 1
fi

HEADER="// Generated by scripts/gen-types.sh from the LOCAL post-migration schema; do not edit by hand.
// CI regenerates this file and fails when the committed copy drifts.
"

generate() {
  pnpm exec supabase gen types typescript --db-url "$DB_URL" --schema public
}

# Fail-closed validation: the Supabase CLI can print a JSON error object
# (e.g. {"_tag":"Error",...}) to stdout without exiting non-zero. Never
# accept output that does not look like the generated TypeScript module.
validate_generated() {
  local file="$1"
  if ! grep -q 'export type Json' "$file" ||
    ! grep -q 'public: {' "$file" ||
    grep -q '"_tag":"Error"' "$file"; then
    echo "ERROR: generated output does not look like valid database types." >&2
    echo "First 20 lines of the output:" >&2
    head -20 "$file" >&2
    exit 1
  fi
}

if [[ "${1:-}" == "--check" ]]; then
  TMP="$(mktemp)"
  trap 'rm -f "$TMP"' EXIT
  { printf '%s\n' "$HEADER"; generate; } > "$TMP"
  validate_generated "$TMP"
  pnpm exec prettier --write "$TMP" --parser typescript >/dev/null
  if ! diff -q "$OUT" "$TMP" >/dev/null; then
    echo "ERROR: $OUT is stale. Run: DB_URL=... pnpm gen:types" >&2
    echo "The freshly generated file follows so it can be recovered from CI logs:" >&2
    echo "===== BEGIN GENERATED database.types.ts ====="
    cat "$TMP"
    echo "===== END GENERATED database.types.ts ====="
    exit 1
  fi
  echo "Generated types are current."
else
  TMP="$(mktemp)"
  trap 'rm -f "$TMP"' EXIT
  { printf '%s\n' "$HEADER"; generate; } > "$TMP"
  validate_generated "$TMP"
  cat "$TMP" > "$OUT"
  pnpm exec prettier --write "$OUT" >/dev/null
  echo "Wrote $OUT"
fi
